---
abstract: "Teng's plugin which enables/disables suppress_row_objects with guard object."
author:
  - 'Takuya Tsuchida <tsucchi@cpan.org<gt>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.6.7, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Teng-Plugin-RowObjectCreationSwitcher
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Teng::Plugin::RowObjectCreationSwitcher:
    file: lib/Teng/Plugin/RowObjectCreationSwitcher.pm
    version: 0.01
requires:
  Scope::Guard: 0
  Teng: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/tsucchi/p5-Teng-Plugin-RowObjectCreationSwitcher/issues
  homepage: https://github.com/tsucchi/p5-Teng-Plugin-RowObjectCreationSwitcher
  repository: git://github.com/tsucchi/p5-Teng-Plugin-RowObjectCreationSwitcher.git
version: 0.01
x_contributors:
  - 'Takuya Tsuchida <tsucchi@cpan.org>'
